spring:
  application:
    name: right-dose

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate.ddl-auto: update # create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

api:
  security:
    token:
      secret: my-secret

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
    enabled: true